In [5]:
%matplotlib inline

Author - Soumith Chintala (http://soumith.ch/)


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [6]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [7]:
x = torch.empty(5, 3)
print(x)

tensor([[2.2475e-17, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 2.7606e-43, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.1444e-17],
        [0.0000e+00, 2.7606e-43, 0.0000e+00],
        [2.7606e-43, 0.0000e+00, 0.0000e+00]])


Construct a randomly initialized matrix:



In [8]:
x = torch.rand(5, 3)
print(x)

tensor([[0.9104, 0.0195, 0.9530],
        [0.2895, 0.3013, 0.5935],
        [0.7658, 0.0966, 0.7062],
        [0.3992, 0.2774, 0.7155],
        [0.0739, 0.3166, 0.7494]])


Construct a matrix filled zeros and of dtype long:



In [9]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [10]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [11]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.8503, -0.6511, -0.8723],
        [ 1.3309, -0.8944,  1.0238],
        [ 0.2409, -0.3587, -0.5391],
        [-0.3323, -0.3635, -0.0230],
        [ 0.5860,  1.4071, -1.2805]])


Get its size:



In [12]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [13]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.9208, -0.6252, -0.1224],
        [ 1.6258,  0.0418,  1.7874],
        [ 1.2223, -0.0953, -0.2171],
        [ 0.3360, -0.0439,  0.0998],
        [ 0.9344,  1.7668, -0.7628]])


Addition: syntax 2



In [14]:
print(torch.add(x, y))

tensor([[ 0.9208, -0.6252, -0.1224],
        [ 1.6258,  0.0418,  1.7874],
        [ 1.2223, -0.0953, -0.2171],
        [ 0.3360, -0.0439,  0.0998],
        [ 0.9344,  1.7668, -0.7628]])


Addition: providing an output tensor as argument



In [15]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.9208, -0.6252, -0.1224],
        [ 1.6258,  0.0418,  1.7874],
        [ 1.2223, -0.0953, -0.2171],
        [ 0.3360, -0.0439,  0.0998],
        [ 0.9344,  1.7668, -0.7628]])


Addition: in-place



In [16]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.9208, -0.6252, -0.1224],
        [ 1.6258,  0.0418,  1.7874],
        [ 1.2223, -0.0953, -0.2171],
        [ 0.3360, -0.0439,  0.0998],
        [ 0.9344,  1.7668, -0.7628]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [17]:
print(x[:, 1])

tensor([-0.6511, -0.8944, -0.3587, -0.3635,  1.4071])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [18]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [19]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.0791])
-1.0791062116622925


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <http://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [20]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [21]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [22]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [23]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [24]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([-0.0791], device='cuda:0')
tensor([-0.0791], dtype=torch.float64)
